name: Build Uncompressed Dev CRX

on:
  pull_request:
    branches: [ dev ]
  push:
    branches: [ dev ]

jobs:
  build_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: npm install, build
        run: |
          npm install
          npm run build:dev
      - name: Archive Development artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sparkling-mock-extension-dev
          path: |
            dist