name: Build Uncompressed CRX

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build_artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: npm install, build
        run: |
          npm install
          npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-files
          path: |
            dist